#define PROJECT_NAME "TABGCppServer"
#define PROJECT_VERSION_MAJOR 0
#define PROJECT_VERSION_MINOR 1
#define PROJECT_VERSION_PATCH 0
#define VERSION_BRANCH imgui
#define VERSION_COMMIT 5d27e42
#define VERSION_FULL "0.1.0-imgui-5d27e42"
