#define PROJECT_NAME "TABGCppServer"
#define PROJECT_VERSION_MAJOR 0
#define PROJECT_VERSION_MINOR 1
#define PROJECT_VERSION_PATCH 0
#define VERSION_BRANCH main
#define VERSION_COMMIT c0252d6
#define VERSION_FULL "0.1.0-main-c0252d6"
